### ISSUE TITLE
Erreur "PRONOTE_RESOURCES_NOT_READY" lors de la récupération des évaluations

### ISSUE THREAD

**Issue by Vilerio** [maelgangloff/scolengo-api#27]
Lorsque je souhaite utiliser la fonction _getEvaluation()_, de la façon suivante :

```js
Skolengo.fromConfigObject(config).then(async user => {
  const infoUser = await user.getUserInfo()
  const studentId = infoUser.id;
  const periodId = '1'; 

  const limit = 20; 
  const offset = 0;
  const notes = await user.getEvaluation(studentId, periodId, limit, offset);
  console.log('Voici les notes :', notes);
}).catch((error) => {
  console.error('Une erreur s\'est produite :', error);
});
```
J'obtiens l'erreur suivante (chemins d'accès modifiés, ils sont à la base absolus) :

```
PRONOTE_RESOURCES_NOT_READY: Pronote resources are not yet ready, please try again in 500 ms
    at Skolengo.request (./node_modules/scolengo-api/dist/index.js:926:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Skolengo.getEvaluation (./node_modules/scolengo-api/dist/index.js:349:52)
    at async ./main.js:38:17 {
  status: '503',
  detail: 'Pronote resources are not yet ready, please try again in 500 ms'
}
```

**Pour reproduire le problème :**
Le code que j'ai testé est :
```js
Skolengo.fromConfigObject(config).then(async user => {
  const infoUser = await user.getUserInfo()
  const studentId = infoUser.id;
  const periodId = '1'; 

  const limit = 20; 
  const offset = 0;
  const notes = await user.getEvaluation(studentId, periodId, limit, offset);
  console.log('Voici les notes :', notes);
}).catch((error) => {
  console.error('Une erreur s\'est produite :', error);
});
```

**Résultat attendu**
La liste des notes, en fonction des arguments passés à la fonction

**Contexte additionnel**
Version de la librairie : 1.2.0

**Comment by maelgangloff** [comment]
Corrigé dans la version v2.0.0
@Vilerio Merci pour la suggestion et pour ta précieuse aide dans sa résolution ;)
